// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentProjectAPI.Data;

#nullable disable

namespace StudentProjectAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250615134932_UpdateUserModel")]
    partial class UpdateUserModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("StudentProjectAPI.Models.DeliverableEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<int>("EvaluationId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Grade")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("ProjectDeliverableId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId");

                    b.HasIndex("ProjectDeliverableId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("DeliverableEvaluations");
                });

            modelBuilder.Entity("StudentProjectAPI.Models.DeliverableType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedExtensions")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxFileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DeliverableTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowedExtensions = ".pdf,.doc,.docx",
                            MaxFileSize = 10,
                            Name = "Rapport"
                        },
                        new
                        {
                            Id = 2,
                            AllowedExtensions = ".zip,.rar,.tar.gz",
                            MaxFileSize = 50,
                            Name = "Code Source"
                        },
                        new
                        {
                            Id = 3,
                            AllowedExtensions = ".ppt,.pptx,.pdf",
                            MaxFileSize = 20,
                            Name = "Présentation"
                        },
                        new
                        {
                            Id = 4,
                            AllowedExtensions = ".mp4,.avi,.mov",
                            MaxFileSize = 100,
                            Name = "Vidéo"
                        },
                        new
                        {
                            Id = 5,
                            AllowedExtensions = ".jpg,.jpeg,.png",
                            MaxFileSize = 5,
                            Name = "Image"
                        });
                });

            modelBuilder.Entity("StudentProjectAPI.Models.Evaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OverallComments")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OverallGrade")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("StudentProjectAPI.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("StudentProjectAPI.Models.GroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLeader")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("GroupId", "StudentId")
                        .IsUnique();

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("StudentProjectAPI.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGroupProject")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxGroupSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("StudentProjectAPI.Models.ProjectAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StudentId");

                    b.ToTable("ProjectAssignments");
                });

            modelBuilder.Entity("StudentProjectAPI.Models.ProjectDeliverable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeliverableTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeliverableTypeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectDeliverables");
                });

            modelBuilder.Entity("StudentProjectAPI.Models.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeliverableId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long?>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SubmittedByStudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("DeliverableId");

                    b.HasIndex("SubmittedByStudentId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("StudentProjectAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Departement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NiveauEtude")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Departement = "",
                            Email = "prof@school.com",
                            FirstName = "Jean",
                            IsActive = true,
                            LastName = "Dupont",
                            NiveauEtude = "",
                            PasswordHash = "hashedpassword1",
                            Role = "Teacher",
                            Specialite = ""
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Departement = "",
                            Email = "student1@school.com",
                            FirstName = "Marie",
                            IsActive = true,
                            LastName = "Martin",
                            NiveauEtude = "",
                            PasswordHash = "hashedpassword2",
                            Role = "Student",
                            Specialite = ""
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Departement = "",
                            Email = "student2@school.com",
                            FirstName = "Pierre",
                            IsActive = true,
                            LastName = "Durand",
                            NiveauEtude = "",
                            PasswordHash = "hashedpassword3",
                            Role = "Student",
                            Specialite = ""
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Departement = "",
                            Email = "student3@school.com",
                            FirstName = "Sophie",
                            IsActive = true,
                            LastName = "Bernard",
                            NiveauEtude = "",
                            PasswordHash = "hashedpassword4",
                            Role = "Student",
                            Specialite = ""
                        });
                });

            modelBuilder.Entity("StudentProjectAPI.Models.DeliverableEvaluation", b =>
                {
                    b.HasOne("StudentProjectAPI.Models.Evaluation", "Evaluation")
                        .WithMany("DeliverableEvaluations")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentProjectAPI.Models.ProjectDeliverable", null)
                        .WithMany("Evaluations")
                        .HasForeignKey("ProjectDeliverableId");

                    b.HasOne("StudentProjectAPI.Models.Submission", "Submission")
                        .WithMany("Evaluations")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("StudentProjectAPI.Models.Evaluation", b =>
                {
                    b.HasOne("StudentProjectAPI.Models.ProjectAssignment", "Assignment")
                        .WithMany("Evaluations")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentProjectAPI.Models.User", "Teacher")
                        .WithMany("Evaluations")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("StudentProjectAPI.Models.Group", b =>
                {
                    b.HasOne("StudentProjectAPI.Models.Project", "Project")
                        .WithMany("Groups")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("StudentProjectAPI.Models.GroupMember", b =>
                {
                    b.HasOne("StudentProjectAPI.Models.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentProjectAPI.Models.User", "Student")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentProjectAPI.Models.Project", b =>
                {
                    b.HasOne("StudentProjectAPI.Models.User", "Teacher")
                        .WithMany("TeacherProjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("StudentProjectAPI.Models.ProjectAssignment", b =>
                {
                    b.HasOne("StudentProjectAPI.Models.Group", "Group")
                        .WithMany("Assignments")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudentProjectAPI.Models.Project", "Project")
                        .WithMany("Assignments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentProjectAPI.Models.User", "Student")
                        .WithMany("IndividualAssignments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");

                    b.Navigation("Project");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentProjectAPI.Models.ProjectDeliverable", b =>
                {
                    b.HasOne("StudentProjectAPI.Models.DeliverableType", "DeliverableType")
                        .WithMany("ProjectDeliverables")
                        .HasForeignKey("DeliverableTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentProjectAPI.Models.Project", "Project")
                        .WithMany("Deliverables")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliverableType");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("StudentProjectAPI.Models.Submission", b =>
                {
                    b.HasOne("StudentProjectAPI.Models.ProjectAssignment", "Assignment")
                        .WithMany("Submissions")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentProjectAPI.Models.ProjectDeliverable", "Deliverable")
                        .WithMany("Submissions")
                        .HasForeignKey("DeliverableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentProjectAPI.Models.User", "SubmittedByStudent")
                        .WithMany("Submissions")
                        .HasForeignKey("SubmittedByStudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Deliverable");

                    b.Navigation("SubmittedByStudent");
                });

            modelBuilder.Entity("StudentProjectAPI.Models.DeliverableType", b =>
                {
                    b.Navigation("ProjectDeliverables");
                });

            modelBuilder.Entity("StudentProjectAPI.Models.Evaluation", b =>
                {
                    b.Navigation("DeliverableEvaluations");
                });

            modelBuilder.Entity("StudentProjectAPI.Models.Group", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("StudentProjectAPI.Models.Project", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Deliverables");

                    b.Navigation("Groups");
                });

            modelBuilder.Entity("StudentProjectAPI.Models.ProjectAssignment", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("StudentProjectAPI.Models.ProjectDeliverable", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("StudentProjectAPI.Models.Submission", b =>
                {
                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("StudentProjectAPI.Models.User", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("GroupMemberships");

                    b.Navigation("IndividualAssignments");

                    b.Navigation("Submissions");

                    b.Navigation("TeacherProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
